version: '3.9'

services:
  db:
    image: docker.io/library/postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tenderuser"]
      interval: 5s
      retries: 5

  redis:
    image: docker.io/library/redis:7
    restart: always
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      target: dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      WEB3_RPC: ${WEB3_RPC}
      BLOCKCHAIN_PRIVATE_KEY: ${BLOCKCHAIN_PRIVATE_KEY}
      STAMP_CONTRACT_ADDRESS: ${STAMP_CONTRACT_ADDRESS}
      STAMP_ABI_PATH: ${STAMP_ABI_PATH}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build:
      context: .
      target: dev
    command: rq worker blockchain --url redis://redis:6379/0
    volumes:
      - .:/code
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      WEB3_RPC: ${WEB3_RPC}
      BLOCKCHAIN_PRIVATE_KEY: ${BLOCKCHAIN_PRIVATE_KEY}
      STAMP_CONTRACT_ADDRESS: ${STAMP_CONTRACT_ADDRESS}
      STAMP_ABI_PATH: ${STAMP_ABI_PATH}
    depends_on:
      - redis
      - db

  ganache:
    image: docker.io/trufflesuite/ganache:v7.9.1
    command: >
      --host 0.0.0.0
      --port 8545
      --chain.chainId 1337
      --wallet.totalAccounts 10
      --wallet.defaultBalance 1000
      --wallet.mnemonic "siyabonga dev tender bridge test mnemonic"
    ports:
      - "8545:8545"
    volumes:
      - ganache_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  ganache_data:

